---
# tasks file for httpd-netology
- name: Install the latest version of httpd YUM
  ansible.builtin.yum:
    name: httpd
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
- name: Install the latest version of httpd APT
  ansible.builtin.apt:
    name: httpd
    state: latest
  when: ansible_facts['os_family'] == "Debian"
- name: "Make index.html file"
  template:
    src: ./templates/index.html.j2
    dest: "/var/www/html/index.html"
- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
- name: Make sure a httpd is restarted and enabled
  ansible.builtin.systemd:
    state: restarted
    name: httpd
    enabled: true 
- name: Check that you can connect (GET) to a page and it returns a status 200
  ansible.builtin.uri:
    url: http://{{ ansible_all_ipv4_addresses [1] }} 