---
- name: "Change MOTD"
  hosts: all
  become: true

  tasks:
  - name: "Make MOTD file"
    template:
      src: ./templates/template2.j2
      dest: "/etc/motd.txt"
  - name: "Edit sshd_config"
    ansible.builtin.lineinfile:
      dest: "/etc/ssh/sshd_config"
      line: "Banner /etc/motd.txt"
      regexp: "^(#)?Banner"
    notify:
    - Restart sshd  
  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
...