---
- name: "Download and unarchive"
  hosts: net1,net2
  tasks:
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /tmp/netology/kafka
      state: directory
      mode: '0755'
  - name: Unarchive a file that needs to be downloaded
    ansible.builtin.unarchive:
      src: https://downloads.apache.org/kafka/3.4.0/kafka_2.13-3.4.0.tgz
      dest: /tmp/netology/kafka
      remote_src: yes

...